name: Deploy Fetch CF to GCP

on:
  push:
    branches: [ "gsheet" ]

env:
  PROJECT_ID: defender-bot
  SERVICE: defender-api-fetch
  REGION: europe-west1

jobs:
  deploy:
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: 'actions/checkout@v3'

      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v1.1.1'
        with:
          credentials_json: '${{ secrets.DEFENDER_BOT_SRV_ACC_JSON }}'

      - name: Deploy to GCP
        id: 'deploy'
        uses: 'google-github-actions/deploy-cloud-functions@v1'
        with:
          name: ${{ env.SERVICE }}
          region: ${{ env.REGION }}
          env_vars: GOOGLE_PROJECT_ID=fair-alliance-401708,SECRET_GOOGLE_SRV_ACC_JSON=SRV_ACC_CRED_JSON
          runtime: "python311"
          source_dir: fetch
          entry_point: fetch
          https_trigger_security_level: secure_always
          ingress_settings: ALLOW_ALL
          memory_mb: 128M
          min_instances: 0
          max_instances: 10

      - name: Show Output
        run: echo ${{ steps.deploy.outputs.url }}
