name: Deploy to Cloud Run from Source

on:
  push:
    branches: [ "master" ]

env:
  PROJECT_ID: start-ax
  SERVICE: stwar-phver-prod
  REGION: us-central1

jobs:
  deploy:
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: 'actions/checkout@v3'

      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v1.1.1'
        with:
          credentials_json: '${{ secrets.SRV_ACC_JSON }}'

      - name: Deploy to GCP
        id: 'deploy'
        uses: 'google-github-actions/deploy-cloud-functions@v1'
        with:
          name: ${{ env.SERVICE }}
          runtime: 'nodejs16'

      - name: Show Output
        run: echo ${{ steps.deploy.outputs.url }}
